# Generated by Django 2.2.27 on 2022-03-11 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employeeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=64, verbose_name='препарат')),
                ('cost', models.BigIntegerField(verbose_name='стоимость')),
                ('recipe', models.BooleanField(default=False, verbose_name='рецепт')),
                ('indications', models.TextField(verbose_name='показания')),
                ('storage_conditions', models.TextField(verbose_name='условия хранения')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeeapp.Branch', verbose_name='филиал')),
            ],
        ),
        migrations.CreateModel(
            name='FormOfRelease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='форма выпуска')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='отчество')),
                ('birthday_date', models.DateField(verbose_name='дата рождения')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_date', models.DateTimeField(auto_now_add=True, verbose_name='дата рецепта')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugsapp.Patient', verbose_name='пациент')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(verbose_name='количество')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugsapp.Drug', verbose_name='препарат')),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugsapp.Recipe', verbose_name='номер рецепта')),
            ],
        ),
        migrations.AddField(
            model_name='drug',
            name='form_of_release',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugsapp.FormOfRelease', verbose_name='форма выпуска'),
        ),
    ]
