# Generated by Django 2.2.27 on 2022-03-11 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название филиала')),
                ('branch_head', models.CharField(max_length=64, verbose_name='руководитель')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='название должности')),
                ('experience', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, verbose_name='требуемый опыт (лет)')),
                ('salary', models.BigIntegerField(unique=True, verbose_name='оклад')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('first_name', models.CharField(max_length=64, verbose_name='имя')),
                ('last_name', models.CharField(max_length=64, verbose_name='фамилия')),
                ('patronymic', models.CharField(max_length=64, verbose_name='отчество')),
                ('passport_num', models.BigIntegerField(unique=True, verbose_name='серия и номер паспорта')),
                ('passport_date', models.DateField(verbose_name='дата выдачи паспорта')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='телефон')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='электронная почта')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeeapp.Branch', verbose_name='филиал')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employeeapp.Position', verbose_name='должность')),
            ],
        ),
        migrations.CreateModel(
            name='Vacation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacation_start', models.DateField(verbose_name='начало отпуска')),
                ('vacation_end', models.DateField(verbose_name='конец отпуска')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.Staff', verbose_name='ID сотрудника')),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary_date', models.DateField(verbose_name='дата выплаты зарплаты')),
                ('salary', models.BigIntegerField(verbose_name='зарплата')),
                ('salary_bonus', models.BigIntegerField(default=0, verbose_name='премия')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employeeapp.Staff', verbose_name='ID сотрудника')),
            ],
        ),
    ]
