# Generated by Django 2.2.27 on 2022-03-11 20:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('drugsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='UUID')),
                ('name', models.CharField(max_length=64, verbose_name='поставщик')),
                ('address', models.CharField(max_length=200, verbose_name='адрес')),
                ('phone', models.BigIntegerField(unique=True, verbose_name='телефон')),
            ],
        ),
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supply_date', models.DateTimeField(auto_now_add=True, verbose_name='дата поставки')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplyapp.Supplier', verbose_name='поставщик')),
            ],
        ),
        migrations.CreateModel(
            name='SuppliedDrug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(verbose_name='количество')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drugsapp.Drug', verbose_name='препарат')),
                ('supply_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='supplyapp.Supply', verbose_name='поставщик')),
            ],
        ),
    ]
